### ISSUE TITLE
Doesn't work in any capacity

### ISSUE THREAD

**Issue by Marrionetta** [BigCuteDonut/Chat-Translation-Tool#7]
Before It was as simple as launching it and it would automatically log and translate chat and translate whatever i put in the chat box.
Now It doesn't log any chat, doesn't even fail to translate it just straight up ignores the log and I can't push enter to translate anything I type. It won't even attempt to translate it. It just refuses to send the text from the chat box to the log area.
![pso2_pLh77LCIFj](https://user-images.githubusercontent.com/88773456/156583560-00c96038-91f0-488b-8390-61ba721a3590.png)
![pso2_xFRXooHVQG](https://user-images.githubusercontent.com/88773456/156583586-ade70fe0-e885-4660-a8e7-2b0f49e070d9.png)

**Comment by BigCuteDonut** [comment]
Sorry for late response(need to update email on github), I will look into this. Could be related to permissions problems, especially if you are running PSO2 as administrator and not the translator.

**Comment by BigCuteDonut** [comment]
![image](https://user-images.githubusercontent.com/41323904/159848708-ec6f7994-528b-4738-b714-24212f522191.png)
Can't reproduce this on my end.
### Troubleshooting
- Check if the %UserProfile%\Documents\SEGA\PHANTASYSTARONLINE2\log_ngs directory exists.
- Confirm log_ngs contains txt files.
- From the chat translator folder, try running bin\ChatTranslator.exe as administrator. Test if working.
- Confirm latest ChatLog txt in log_ngs file matches the date you most recently launched PSO2 (give or take a day). Format is ChatLogYYYYMMDD_00.txt
- Remove all files from PHANTASYSTARONLINE2\log (not log_ngs).  Test if working.
- Remove all files from PHANTASYSTARONLINE2\log_ngs.  Test if working.
- From the chat translator folder, try running bin\ChatTranslator.exe as administrator. Test if working.
- Check if translator works in PSO2 lobby.
